# permissions for end users to edit haproxyconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxyconfig-editor-role
rules:
- apiGroups:
  - haproxy-opeartor.my.domain
  resources:
  - haproxyconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - haproxy-opeartor.my.domain
  resources:
  - haproxyconfigs/status
  verbs:
  - get
